export const navbar = [
  {
    name: "Home",
    path: "/",
  },
  {
    name: "Movies",
    path: "/search/movie",
  },
  {
    name: "Shows",
    path: "/search/tv",
  },
  {
    name: "Watchlist",
    path: "/watchlist",
  },
];

export const genres = {
  movie: [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documental" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Terror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mistery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science fiction" },
    { id: 10770, name: "TV Movie" },
    { id: 53, name: "Suspense" },
    { id: 10752, name: "Belic" },
    { id: 37, name: "Western" },
  ],
  tv: [
    { id: 10759, name: "Action & Adventure" },
    { id: 16, name: "Animación" },
    { id: 35, name: "Comedia" },
    { id: 80, name: "Crimen" },
    { id: 99, name: "Documental" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Familia" },
    { id: 10762, name: "Kids" },
    { id: 9648, name: "Misterio" },
    { id: 10763, name: "News" },
    { id: 10764, name: "Reality" },
    { id: 10765, name: "Sci-Fi & Fantasy" },
    { id: 10766, name: "Soap" },
    { id: 10767, name: "Talk" },
    { id: 10768, name: "War & Politics" },
    { id: 37, name: "Western" },
  ],
};
